version: '3.6'

networks:
  net:
    driver: overlay
    attachable: true

services:

  eventlogger:
    image: matjaz99/eventlogger:0.2.3
    ports:
      - 7073:8080
    networks:
      - net
    environment:
      - TZ=${TZ}
      - SIMPLELOGGER_FILENAME=/opt/eventlogger/log/eventlogger.log
      - EVENTLOGGER_DATA_RETENTION_DAYS=30
      - EVENTLOGGER_DB_POOL_SIZE=3
      # choose storage type: mongodb or memory
      - EVENTLOGGER_STORAGE_TYPE=mongodb
      - EVENTLOGGER_MONGODB_CONNECTION_STRING=mongodb://admin:mongodbpassword@172.29.18.22:27017/?authSource=admin
      - EVENTLOGGER_MONGODB_CONNECT_TIMEOUT_SEC=5
      - EVENTLOGGER_MONGODB_READ_TIMEOUT_SEC=30
    volumes:
      - /var/log:/opt/eventlogger/log
    deploy:
      mode: replicated
      replicas: 1
