version: '3.6'

networks:
  net:
    driver: overlay
    attachable: true

services:

  eventlogger:
    image: matjaz99/eventlogger:0.3.4
    ports:
      - 7073:8080
    networks:
      - net
    environment:
      - TZ=${TZ}
      - SIMPLELOGGER_FILENAME=/opt/eventlogger/log/eventlogger.log
      - EVENTLOGGER_EVENT_RULES_CONFIG_FILE=/opt/eventlogger/rules/event_rules.yml
      - EVENTLOGGER_DATA_RETENTION_DAYS=30
      - EVENTLOGGER_DB_POOL_SIZE=3
      # choose storage type: mongodb, opensearch or memory
      - EVENTLOGGER_STORAGE_TYPE=mongodb
      - EVENTLOGGER_MONGODB_CONNECTION_STRING=mongodb://admin:mongodbpassword@192.168.0.170:27017/?authSource=admin
      - EVENTLOGGER_MONGODB_CONNECT_TIMEOUT_SEC=5
      - EVENTLOGGER_MONGODB_READ_TIMEOUT_SEC=30
      - EVENTLOGGER_MONGODB_FLUSH_INTERVAL_SEC=5
      - EVENTLOGGER_MONGODB_BATCH_INSERT_MAX_SIZE=100
      - EVENTLOGGER_OPENSEARCH_CONNECTION_STRING=https://admin:admin@192.168.0.170:9200
      - EVENTLOGGER_OPENSEARCH_CONNECT_TIMEOUT_SEC=5
      - EVENTLOGGER_OPENSEARCH_READ_TIMEOUT_SEC=30
      - EVENTLOGGER_OPENSEARCH_INDEX_NAME=eventlogger
      - EVENTLOGGER_ALARM_DESTINATION=http://alertmonitor:8080/alertmonitor/webhook/eventlogger
    volumes:
      - /var/log:/opt/eventlogger/log
      - ./rules/event_rules.yml:/opt/eventlogger/rules/event_rules.yml
    deploy:
      mode: replicated
      replicas: 1
