version: '3.6'

networks:
  monitoring_network:
    driver: overlay
    attachable: true

services:

  eventlogger:
    image: matjaz99/eventlogger:0.2.0
    ports:
      - 7073:8080
    networks:
      - monitoring_network
    environment:
      - TZ=${TZ}
      - SIMPLELOGGER_FILENAME=/opt/eventlogger/log/eventlogger.log
      - EVENTLOGGER_DATA_RETENTION_DAYS=30
      - EVENTLOGGER_STORAGE_TYPE=mongodb
      - EVENTLOGGER_MONGODB_CONNECTION_STRING=mongodb://admin:mongodbpassword@172.29.18.22:27017/?authSource=admin
    volumes:
      - /var/log:/opt/eventlogger/log
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 15s
      timeout: 5s
      retries: 5
