{
 "title": "eventlogger v1.0",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(eventlogger_build_info{app=\"EventLogger\"} , instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eventlogger_build_info{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Eventlogger version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "eventlogger_build_info{instance=\"$node\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Total events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eventlogger_events_total{instance=\"$node\"})",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Received events from hosts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(eventlogger_events_total{instance=\"$node\"}[1m])) by (host) * 15",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Received requests from hosts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "irate(eventlogger_http_requests_total{instance=\"$node\"}[1m]) * 15",
     "legendFormat": "{{remotehost}}"
    }
   ]
  },
  {
   "title": "Received request size",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(eventlogger_http_requests_size_total{instance=\"$node\"}[5m]) * 15",
     "legendFormat": "{{remotehost}}"
    }
   ]
  },
  {
   "title": "Number of DB actions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(irate(eventlogger_db_duration_seconds_count{instance=\"$node\"}[5m])) by (action) * 15",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "DB errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(eventlogger_db_errors_total{instance=\"$node\"}[5m])) * 15",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "DB action average time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(eventlogger_db_duration_seconds_sum{instance=\"$node\"}[5m])) by (action) / sum(rate(eventlogger_db_duration_seconds_count{instance=\"$node\"}[5m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Percentage of DB actions with response time less than 100ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(eventlogger_db_duration_seconds_bucket{instance=\"$node\", le=\"0.1\"}[5m])) by (action) / sum(rate(eventlogger_db_duration_seconds_count{instance=\"$node\"}[5m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Duration within which DB has processed N% of actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(eventlogger_db_duration_seconds_bucket{instance=\"$node\"}[5m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(eventlogger_db_duration_seconds_bucket{instance=\"$node\"}[5m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(eventlogger_db_duration_seconds_bucket{instance=\"$node\"}[5m])) by (le))",
     "legendFormat": "90%"
    }
   ]
  }
 ]
}