{
 "title": "Eventlogger - events",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(event_error_count_total[5m])) by (host, ident) * 15",
     "legendFormat": "{{ident}}@{{host}}"
    }
   ]
  },
  {
   "title": "Command not found",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(event_command_not_found_total[5m])) by (host, ident) * 15",
     "legendFormat": "{{ident}}@{{host}}"
    }
   ]
  },
  {
   "title": "Session started",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(event_session_started_total[5m])) by (host, ident) * 15",
     "legendFormat": "{{ident}}@{{host}}"
    }
   ]
  }
 ]
}