{
 "title": "eventlogger v0.3.0",
 "tags": [
  "eventlogger",
  "monis"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(eventlogger_build_info{app=\"EventLogger\"} , instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Events processed",
   "type": "stat",
   "description": "Total number of incoming events since start.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eventlogger_events_total{instance=\"$node\"})",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Events per hour",
   "type": "stat",
   "description": "Number of events received in the last hour. This is estimated value, based on average rate of incoming events over the last hour. Not necessarily equal to absolute number of events received in last hour.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(eventlogger_events_total{instance=\"$node\"}[1h])) * 3600",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "eventlogger_memory_total_bytes{instance=\"$node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "eventlogger_memory_free_bytes{instance=\"$node\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eventlogger_available_processors{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "DB insert bulk size",
   "type": "stat",
   "description": "Number of events which are stored in DB with single bulk insert operation.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eventlogger_db_bulk_insert_size{instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received requests from hosts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(irate(eventlogger_http_requests_total{instance=\"$node\"}[1m])) by (remotehost) * 15",
     "legendFormat": "{{remotehost}}"
    }
   ]
  },
  {
   "title": "Received request size",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(eventlogger_http_requests_size_total{instance=\"$node\"}[5m])) by (remotehost) * 15",
     "legendFormat": "{{remotehost}}"
    }
   ]
  },
  {
   "title": "Received requests by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 4 },
   "targets": [
    {
     "expr": "sum(irate(eventlogger_http_requests_total{instance=\"$node\"}[1m])) by (webhook) * 15",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "DB waiting queue size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "eventlogger_db_buffer_size{instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received events from hosts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(eventlogger_events_total{instance=\"$node\"}[1m])) by (host) * 15",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Number of DB actions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(irate(eventlogger_db_duration_seconds_count{instance=\"$node\"}[5m])) by (action) * 15",
     "legendFormat": "{{action}}"
    },
    {
     "expr": "sum(irate(eventlogger_db_errors_total{instance=\"$node\"}[5m])) * 15",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Received events by ident",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum(irate(eventlogger_events_total{instance=\"$node\"}[1m])) by (ident) * 15)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "DB action average time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(eventlogger_db_duration_seconds_sum{instance=\"$node\"}[5m])) by (action) / sum(rate(eventlogger_db_duration_seconds_count{instance=\"$node\"}[5m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Rule actions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(eventlogger_rule_actions_total[5m]) * 15",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Duration within which DB has processed N% of actions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(eventlogger_db_duration_seconds_bucket{instance=\"$node\"}[5m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(eventlogger_db_duration_seconds_bucket{instance=\"$node\"}[5m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(eventlogger_db_duration_seconds_bucket{instance=\"$node\"}[5m])) by (le))",
     "legendFormat": "90%"
    }
   ]
  },
  {
   "title": "Average rule evaluation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(eventlogger_rule_evaluation_seconds_sum{instance=\"$node\"}[1m])) by (endpoint) / sum(rate(eventlogger_rule_evaluation_seconds_count{instance=\"$node\"}[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Percentage of DB actions with response time less than 100ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(eventlogger_db_duration_seconds_bucket{instance=\"$node\", le=\"0.1\"}[5m])) by (action) / sum(rate(eventlogger_db_duration_seconds_count{instance=\"$node\"}[5m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Eventlogger version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "eventlogger_build_info{instance=\"$node\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eventlogger_build_info{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Ignored events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(irate(eventlogger_events_ignored_total{instance=\"$node\"}[1m])) by (reason) * 15",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "sum(irate(eventlogger_requests_ignored_total{instance=\"$node\"}[1m])) by (reason) * 15",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Alarm buffer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "targets": [
    { "expr": "eventlogger_alarm_buffer_size", "legendFormat": "{{reason}}" }
   ]
  }
 ]
}