{
 "title": "eventlogger v1.0",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eventlogger_build_info" }
   ]
  },
  {
   "title": "Total events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(eventlogger_events_total)", "legendFormat": "{{action}}" }
   ]
  },
  {
   "title": "Received message size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(eventlogger_webhook_messages_size_total[5m]) * 15",
     "legendFormat": "{{remotehost}}"
    }
   ]
  },
  {
   "title": "Received messages from hosts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "irate(eventlogger_webhook_messages_received_total[1m]) * 15",
     "legendFormat": "{{remotehost}}"
    }
   ]
  },
  {
   "title": "Received events from hosts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(irate(eventlogger_events_total[1m])) by (host) * 15",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Number of DB actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "irate(eventlogger_db_duration_seconds_count[5m]) * 15",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "DB action average time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(eventlogger_db_duration_seconds_sum[1m]) / rate(eventlogger_db_duration_seconds_count[1m])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Percentage of DB actions with response time less than 100ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(eventlogger_db_duration_seconds_bucket{le=\"0.1\"}[5m])) by (action) / sum(rate(eventlogger_db_duration_seconds_count[5m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Duration within which DB has processed N% of actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(eventlogger_db_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(eventlogger_db_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(eventlogger_db_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "90%"
    }
   ]
  }
 ]
}